title: Kanwar Gill
description: Engineering (SWE) | Teaching (OCT)
baseurl: ""
url: "https://www.kanwargill.ca"

# Favicon
favicon: /img/favicon-16x16.png

# Theme settings
remote_theme: b2a3e8/jekyll-theme-console
plugins:
  - jekyll-seo-tag
  - jekyll-remote-theme

# Style: dark, light, hacker, nord
style: hacker

# Header pages
header_pages:
  - index.md
  - about.md
  - contact.md

# Footer
footer: 'Copyright &copy; 2026 Kanwar Gill | <a href="https://github.com/KanwarGill">GitHub</a> | <a href="https://www.linkedin.com/in/gillkanwar/">LinkedIn</a>'

# Author info
author:
  name: Kanwar Gill
  email: contact@kanwargill.ca

# Exclude from build
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - README.md
  - LICENCE
  - Rakefile
  - freelancer-theme-jekyll.gemspec
  - screenshot.png
  - mail
  - js
  - css/font-awesome
